apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

resources:
  - ../../../../../../base/storetheindex-single
  - ingress.yaml

namePrefix: mya-

commonLabels:
  name: mya

secretGenerator:
  - name: identity
    behavior: replace
    files:
      - identity.key=identity.key.encrypted # 12D3KooWHGHu3jVjya9sDSAYRmAVtUnQGTwnWeqan1smfJdjzscB

configMapGenerator:
  - name: config
    behavior: replace
    files:
      - config=config.json

patchesStrategicMerge:
  - pvc.yaml
  - deployment.yaml

images:
  - name: storetheindex
    newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/storetheindex/storetheindex
    newTag: 20221028063024-9ec19b3a4e3e8efc4a06d45e4a4724fb32d28620
