apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

resources:
  - ../../../../../base/indexstar
  - ingress.yaml
  - pod-monitor.yaml

patchesStrategicMerge:
  - deployment.yaml

replicas:
  - name: indexstar
    count: 10

images:
  - name: indexstar
    newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/indexstar/indexstar
    newTag: 20220909145118-fce1f29db9166941564d8bd8cf127a029f213364
